"""Initial schema with UserCategory and multi-tenant categories

Revision ID: 93994adc28c3
Revises: 
Create Date: 2026-02-17 10:53:42.764553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93994adc28c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nombre', name='uq_user_categoria_nombre')
    )
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_index(op.f('ix_user_categories_user_id'), 'user_categories', ['user_id'], unique=False)
    op.add_column('categories', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_categories_nombre'), 'categories', ['nombre'], unique=True)
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('user_category_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'user_categories', ['user_category_id'], ['id'])
    op.alter_column('users', 'alias_bancario',
               existing_type=sa.TEXT(),
               type_=encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('users', 'cvu',
               existing_type=sa.TEXT(),
               type_=encryption.EncryptedString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cvu',
               existing_type=encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'alias_bancario',
               existing_type=encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.alter_column('expenses', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expenses', 'user_category_id')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'created_at')
    op.drop_index(op.f('ix_categories_nombre'), table_name='categories')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'descripcion')
    op.drop_index(op.f('ix_user_categories_user_id'), table_name='user_categories')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
