"""drop_contacts_split_tables

Revision ID: b311c01b4be1
Revises: 46a458e0a045
Create Date: 2026-06-10 11:35:40.078609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b311c01b4be1'
down_revision: Union[str, Sequence[str], None] = '46a458e0a045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_split_expenses_id', table_name='split_expenses')
    op.drop_table('split_expenses')
    op.drop_index('ix_split_group_members_id', table_name='split_group_members')
    op.drop_table('split_group_members')
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_split_groups_id', table_name='split_groups')
    op.drop_table('split_groups')
    op.drop_index('ix_split_expense_participants_id', table_name='split_expense_participants')
    op.drop_table('split_expense_participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_expense_participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('share_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['split_expenses.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['split_group_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_split_expense_participants_id', 'split_expense_participants', ['id'], unique=False)
    op.create_table('split_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_split_groups_id', 'split_groups', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('alias_bancario', sa.VARCHAR(), nullable=True),
    sa.Column('cvu', sa.VARCHAR(), nullable=True),
    sa.Column('linked_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    op.create_table('split_group_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('is_creator', sa.BOOLEAN(), nullable=True),
    sa.Column('display_name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_split_group_members_id', 'split_group_members', ['id'], unique=False)
    op.create_table('split_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), nullable=False),
    sa.Column('importe', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('paid_by_member_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
    sa.ForeignKeyConstraint(['paid_by_member_id'], ['split_group_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_split_expenses_id', 'split_expenses', ['id'], unique=False)
    # ### end Alembic commands ###
