"""add_dia_vencimiento_to_gasto_fijo

Revision ID: de788c80488e
Revises: c5d4e3f2a1b0
Create Date: 2026-06-04 11:41:33.641268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de788c80488e'
down_revision: Union[str, Sequence[str], None] = 'c5d4e3f2a1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_fijos', sa.Column('dia_vencimiento', sa.Integer(), nullable=True))
    op.add_column('gastos_fijos', sa.Column('dias_anticipacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos_fijos', 'dias_anticipacion')
    op.drop_column('gastos_fijos', 'dia_vencimiento')
    # ### end Alembic commands ###
